import { randomUUID } from 'crypto'
import { NextRequest, NextResponse } from 'next/server'
import { Resend } from 'resend'
import { put } from '@vercel/blob'
import {
  type Answers,
  SCREENS_BY_ID,
  formatAnswer,
  phonosemanticProfile,
  getReportModules,
} from '@/lib/schema'
import { type ProjectState, DEFAULT_PROJECT } from '@/lib/project'
import { generateNamingDirections, type NamingResult } from '@/lib/naming'

const TO_EMAIL   = 'info@kshetejsareen.com'
const FROM_EMAIL = process.env.FROM_EMAIL ?? 'onboarding@resend.dev'
const BASE_URL   = process.env.NEXT_PUBLIC_BASE_URL ?? 'https://brand-naming-tool.vercel.app'

// ─── Brief token ──────────────────────────────────────────────────────────────
// A random, unguessable ID rather than a base64 dump of the raw answers — the
// old scheme put a client's full unencrypted diagnostic in the URL bar with no
// expiry and no auth. The token now just addresses a (non-public) Blob record.

function generateBriefToken(): string {
  return randomUUID().replace(/-/g, '')
}

// ─── Report sections — the one place answers become human-readable text ──────
// Both the Claude-ready doc and the internal email render from this, so their
// substantive content can never drift apart from each other or from the
// question definitions in src/lib/schema.ts.

interface ReportField { key: string; value: string }
interface ReportSection { num: string; label: string; fields: ReportField[] }

function buildReportSections(a: Answers): ReportSection[] {
  return getReportModules().map((mod) => {
    // Module 03 is a derived profile (phonosemantic score + explicit cultural
    // register), not a raw per-question dump — the individual word-pair
    // choices are noise once they're summarized.
    if (mod.num === '03') {
      const profile = phonosemanticProfile(a)
      return {
        num: mod.num,
        label: mod.label,
        fields: [
          { key: 'Sonic profile', value: `${profile.direction} (${profile.score}/${profile.total} soft)` },
          { key: 'Market scope', value: formatAnswer('market_scope', a.market_scope) },
          { key: 'Cultural register', value: formatAnswer('cultural_register', a.cultural_register) },
        ],
      }
    }
    return {
      num: mod.num,
      label: mod.label,
      fields: mod.ids.map((id) => ({
        key: SCREENS_BY_ID[id].briefLabel,
        value: formatAnswer(id, a[id]),
      })),
    }
  })
}

// ─── Claude-ready Phase 2 document (plain text, uploaded to Claude) ───────────
// If in-house generation succeeded, this shows the actual results. If it
// didn't (no API key configured, or the call failed), it falls back to the
// original manual-copy-paste instructions so the studio can still generate
// names by hand — generation is an enhancement, not a hard dependency.

function buildClaudeDoc(a: Answers, briefUrl: string, naming: NamingResult | null): string {
  const sections = buildReportSections(a)
    .map((s) => [
      `━━━ ${s.num} — ${s.label.toUpperCase()} ━━━`,
      ...s.fields.map((f) => `${f.key}: ${f.value}`),
    ].join('\n'))
    .join('\n\n')

  const namingBlock = naming
    ? `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
NAMING DIRECTIONS — generated by Claude
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

${naming.brandCharacter}

${naming.territories.map((t) => `── ${t.premise} ──

${t.names.map((n) => `NAME: ${n.name}
TYPE: ${n.type}
RATIONALE: ${n.rationale}
SONIC FIT: ${n.sonicFit}
DIRECTIONS: ${n.direction}
RISK: ${n.risk}`).join('\n\n')}`).join('\n\n')}`
    : `You are a senior brand strategist at K&A Studios, a boutique brand identity studio based in India. A client has completed the brand naming diagnostic below.

Begin by:
1. Reading all six modules carefully before generating anything
2. Summarising the brand character in 2–3 sharp sentences — who this brand is, not what it does
3. Generating 2-3 naming territories (6-8 names total) grounded in the diagnostic, each a distinct strategic premise (see format below)
4. Asking which territory to develop further

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
NAMING FORMAT — use this structure for each of the 7 names:

NAME: [proposed name]
TYPE: invented / evocative / metaphorical / compound / borrowed / geographical
RATIONALE: 2–3 sentences linking explicitly to specific diagnostic answers
SONIC FIT: why the phonetics match (or intentionally contrast) stated preferences
DIRECTIONS: one concrete extension — tagline territory, visual character, verbal tone
RISK: one honest concern — trademark, pronunciation, cultural meaning

Group names by territory where it emerges naturally.`

  return `━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
K&A STUDIOS — BRAND NAMING BRIEF
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Brief URL: ${briefUrl}
Client: ${a.client_name || '—'} · ${a.business_name || 'Unnamed project'} · ${a.industry || '—'}
Submitted: ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}

${sections}

${namingBlock}`
}

// ─── HTML email ───────────────────────────────────────────────────────────────

function buildEmail(a: Answers, briefUrl: string, naming: NamingResult | null): string {
  const sectionsHtml = buildReportSections(a)
    .map((s) => `
  <div class="section">
    <div class="section-label">${s.num} — ${s.label}</div>
    ${s.fields.map((f) => `<div class="field"><div class="field-key">${f.key}</div><div class="field-val">${f.value}</div></div>`).join('\n    ')}
  </div>`)
    .join('\n')

  const namingHtml = naming
    ? `
  <div class="section">
    <div class="section-label">Naming Directions</div>
    <div class="field-val" style="font-style:italic;margin-bottom:20px;">${naming.brandCharacter}</div>
    ${naming.territories.map((t) => `
    <div style="margin-bottom:20px;">
      <div style="font-size:12px;color:#8a857d;letter-spacing:0.04em;margin-bottom:10px;">${t.premise}</div>
      ${t.names.map((n) => `
      <div style="border:1px solid rgba(236,232,224,0.10);padding:16px 20px;margin-bottom:12px;">
        <div style="font-size:17px;color:#ece8e0;margin-bottom:8px;">${n.name} <span style="font-size:11px;color:#6b6460;">(${n.type})</span></div>
        <div class="field-val" style="margin-bottom:8px;">${n.rationale}</div>
        <div style="font-size:11px;color:#6b6460;margin-bottom:4px;">Sonic fit: ${n.sonicFit}</div>
        <div style="font-size:11px;color:#6b6460;">Risk: ${n.risk}</div>
      </div>`).join('\n')}
    </div>`).join('\n')}
  </div>`
    : `
  <div class="section">
    <div class="section-label">Phase 2 — Next Steps</div>
    <div class="brief-link">
      <div class="field-key" style="margin-bottom:8px;">Brief URL</div>
      <a href="${briefUrl}">${briefUrl}</a>
      <div class="claude-note">The plain-text version of this email is a Claude-ready brief. Upload it to a new Claude conversation to begin naming generation and Phase 2 development.</div>
    </div>
  </div>`

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Brand Naming Brief</title>
<style>
  body { margin: 0; padding: 0; background: #0f0e0d; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #c8c4ba; }
  .wrap { max-width: 660px; margin: 0 auto; padding: 48px 32px; }
  .header { border-bottom: 1px solid rgba(236,232,224,0.12); padding-bottom: 32px; margin-bottom: 40px; }
  .studio { font-size: 11px; letter-spacing: 0.28em; text-transform: uppercase; color: #8a857d; margin-bottom: 8px; }
  .report-title { font-size: 24px; color: #ece8e0; font-weight: 400; margin: 0 0 6px; }
  .report-sub { font-size: 13px; color: #8a857d; }
  .section { margin-bottom: 36px; }
  .section-label { font-size: 10px; letter-spacing: 0.28em; text-transform: uppercase; color: #8a857d; border-bottom: 1px solid rgba(236,232,224,0.08); padding-bottom: 10px; margin-bottom: 18px; }
  .field { margin-bottom: 14px; }
  .field-key { font-size: 10px; letter-spacing: 0.2em; text-transform: uppercase; color: #6b6460; margin-bottom: 4px; }
  .field-val { font-size: 14px; color: #c8c4ba; line-height: 1.65; white-space: pre-wrap; }
  .brief-link { background: rgba(236,232,224,0.03); border: 1px solid rgba(236,232,224,0.10); padding: 20px 24px; margin-top: 8px; }
  .brief-link a { color: #ece8e0; word-break: break-all; font-size: 13px; }
  .claude-note { font-size: 12px; color: #8a857d; margin-top: 10px; line-height: 1.6; }
  .footer { margin-top: 48px; padding-top: 24px; border-top: 1px solid rgba(236,232,224,0.08); font-size: 11px; color: #5a5650; letter-spacing: 0.1em; }
</style>
</head>
<body>
<div class="wrap">
  <div class="header">
    <div class="studio">K&A Studios · Brand Naming Brief</div>
    <div class="report-title">${a.business_name || 'Unnamed Project'}</div>
    <div class="report-sub">${a.client_name || '—'} · ${a.industry || '—'} · ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}</div>
  </div>
${namingHtml}
  <div class="section">
    <div class="section-label">Client</div>
    <div class="field"><div class="field-key">Name</div><div class="field-val">${a.client_name || '—'}</div></div>
    <div class="field"><div class="field-key">Business / Project</div><div class="field-val">${a.business_name || '—'}</div></div>
    <div class="field"><div class="field-key">Email</div><div class="field-val">${a.client_email || '—'}</div></div>
    <div class="field"><div class="field-key">Industry</div><div class="field-val">${a.industry || '—'}</div></div>
    <div class="field"><div class="field-key">Full brief</div><div class="field-val"><a href="${briefUrl}" style="color:#ece8e0;">${briefUrl}</a></div></div>
  </div>
${sectionsHtml}

  <div class="footer">
    K&A Studios · Brand Identity Development · info@kshetejsareen.com<br>
    This brief is confidential and for internal use only.
  </div>
</div>
</body>
</html>`
}

// ─── Route handler ────────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  try {
    const answers = await req.json() as Answers

    const token    = generateBriefToken()
    const briefUrl = `${BASE_URL}/brief/${token}`

    const naming = await generateNamingDirections(answers)
    const project: ProjectState = naming
      ? { ...DEFAULT_PROJECT, status: 'generated', brandCharacter: naming.brandCharacter, territories: naming.territories }
      : DEFAULT_PROJECT

    let emailStatus: 'sent' | 'failed' = 'failed'
    try {
      const resend = new Resend(process.env.RESEND_API_KEY)
      const { data, error } = await resend.emails.send({
        from:    FROM_EMAIL,
        to:      TO_EMAIL,
        subject: `Brand Naming — ${answers.business_name || 'New submission'} · ${answers.client_name || 'Unknown'} · ${answers.industry || ''}`,
        html:    buildEmail(answers, briefUrl, naming),
        text:    buildClaudeDoc(answers, briefUrl, naming),
      })
      if (error) {
        console.error('Resend error:', JSON.stringify(error))
      } else {
        emailStatus = 'sent'
        console.log('Email sent:', data?.id)
      }
    } catch (emailErr) {
      // Email is a best-effort notification — its failure doesn't lose the
      // submission, which is why the Blob write below is unconditional.
      console.error('Email send failed:', emailErr)
    }

    // Blob write is the transaction of record. If it throws, the outer catch
    // returns ok:false so the client can tell the user their submission
    // wasn't saved, instead of silently showing "Thank you" over a lost
    // response.
    await put(`submissions/${token}.json`, JSON.stringify({
      token,
      submittedAt: new Date().toISOString(),
      briefUrl,
      emailStatus,
      answers,
      project,
    }, null, 2), { access: 'public', addRandomSuffix: false })

    return NextResponse.json({ ok: true, briefUrl })
  } catch (err) {
    console.error('Submit error:', err)
    return NextResponse.json({ ok: false }, { status: 500 })
  }
}
